# Generated by Django 3.2.3 on 2021-05-30 22:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_games',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Russian poker'), (2, 'Baccarat'), (3, 'Roulette'), (4, 'Black Jack')], max_length=7),
        ),
    ]
