# Generated by Django 3.2.3 on 2021-05-31 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20210531_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_games',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adminapp.game'),
        ),
    ]
