# Generated by Django 3.2.3 on 2021-06-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20210531_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianPokerBonusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_boundary', models.IntegerField(default=0)),
                ('jackpot_percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='GamePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=255)),
                ('preset_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='RussianPokerSettings',
            fields=[
                ('ante_min', models.IntegerField(default=0)),
                ('bonus_min', models.IntegerField(default=0)),
                ('payout_max', models.IntegerField(default=0)),
                ('preset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminapp.gamepreset')),
                ('bonus_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.russianpokerbonustable')),
            ],
        ),
    ]
