# Generated by Django 3.2.3 on 2021-06-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20210617_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='russianpokerbonustable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='russianpokersettings',
            name='bonus_table',
        ),
        migrations.AddField(
            model_name='russianpokerbonustable',
            name='settings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminapp.russianpokersettings'),
            preserve_default=False,
        ),
    ]
