# Generated by Django 3.2.3 on 2021-06-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20210618_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='russianpokerbonustable',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='russianpokerbonustable',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.russianpokersettings'),
        ),
    ]
