# Generated by Django 3.2.3 on 2021-06-18 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20210618_0802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RussianPokerBonusTable',
        ),
    ]
