# Generated by Django 3.2.3 on 2021-06-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_delete_russianpokerbonustable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RussianPokerBonusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_boundary', models.IntegerField(default=0)),
                ('jackpot_percentage', models.IntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.russianpokersettings')),
            ],
        ),
    ]
