# Generated by Django 3.2.3 on 2021-06-21 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_remove_gamepreset_preset_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteMinMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='russianpokerbonustable',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_table', to='adminapp.russianpokersettings'),
        ),
        migrations.CreateModel(
            name='RouletteSettings',
            fields=[
                ('preset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminapp.gamepreset')),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='adminapp.rouletteminmax')),
                ('corner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corner', to='adminapp.rouletteminmax')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dozen', to='adminapp.rouletteminmax')),
                ('even_chances', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='even_chances', to='adminapp.rouletteminmax')),
                ('orphelins', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orphelins', to='adminapp.rouletteminmax')),
                ('series_5_8', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_5_8', to='adminapp.rouletteminmax')),
                ('six_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='six_line', to='adminapp.rouletteminmax')),
                ('split', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='adminapp.rouletteminmax')),
                ('straight_up', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='straight_up', to='adminapp.rouletteminmax')),
                ('street', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='street', to='adminapp.rouletteminmax')),
                ('voisins_de_zero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voisins_de_zero', to='adminapp.rouletteminmax')),
                ('zero_spiel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zero_spiel', to='adminapp.rouletteminmax')),
            ],
        ),
    ]
